/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
 * Generated on: 11-Jun-2021 11:52:06
 */

#ifndef IIR_H
#define IIR_H

 /*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Order               : 6
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 * Filter type coefs   : single-precission float

 * N      = 6;   % Order
 * Fpass1 = 5;   % First Passband Frequency
 * Fpass2 = 50;  % Second Passband Frequency
 * Apass  = 1;   % Passband Ripple (dB)
 * Astop  = 80;  % Stopband Attenuation (dB)

 */
#define NUMERATOR_TAPS 7
#define DENOMINATOR_TAPS 7

float B_numerator_taps[7] = {
   0.009276497178,-0.002606216352, -0.02261597291,              0,  0.02261597291,
   0.002606216352,-0.009276497178
};

float A_denominator_taps[7] = {
                0,   -5.135499001,    11.23368645,   -13.44532967,    9.306217194,
     -3.532883406,    0.573856473
};

#endif


