/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
 * Generated on: 11-Jun-2021 13:04:34
 */

#ifndef IIR_H
#define IIR_H

 /*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Order               : 6
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 * Filter type coefs   : int32
 */


#define NUMERATOR_TAPS 7
#define DENOMINATOR_TAPS 7


int32_t B_numerator_taps[7] = {
      19921126,    -5596807,   -48567431,           0,    48567431,     5596807,
     -19921126
};


int32_t A_denominator_taps[7] = {
    2147483647, -2147483648,  2147483647, -2147483648,  2147483647, -2147483648,
    1232347396
};

#endif

