/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
 * Generated on: 11-Jun-2021 13:04:44
 */


#ifndef IIR_H
#define IIR_H

 /*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Order               : 6
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 * Filter type coefs   : int8
 */


#define NUMERATOR_TAPS 7
#define DENOMINATOR_TAPS 7

int8_T B_numerator_taps[7] = {
      1,    0,   -3,    0,    3,    0,   -1
};


int8_T A_denominator_taps[7] = {
    127, -128,  127, -128,  127, -128,   73
};

#endif

