/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
 * Generated on: 11-Jun-2021 13:04:24
 */

#ifndef IIR_H
#define IIR_H

 /*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Order               : 6
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 * Filter type coefs   : int16
 */


#define NUMERATOR_TAPS 7
#define DENOMINATOR_TAPS 7

int16_t B_numerator_taps[7] = {
//      304,    -85,   -741,      0,    741,     85,   -304
		18,    -6,   -47,     0,    46,     5,   -19
};

int16_t A_denominator_taps[7] = {
//    0, -32768,  32767, -32768,  32767, -32768,  18804
0,      -10518,       23006,      -27537,       19059,       -7236,        1175
};

#endif

