/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
 * Generated on: 11-Jun-2021 21:52:37
 */

#ifndef NOTCH_H
#define NOTCH_H


/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Order			   			 : Minimum order : 2
 * Numerator Length    : 3
 * Denominator Length  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

#define NOTCH_NUMERATOR 3
#define NOTCH_DENOMINATOR 3

float NOTCH_NUM[3] = {
    32457, -32768,  32457
};

float NOTCH_DEN[3] = {
    32767, -32768,  32145
};

#endif

