/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
 * Generated on: 15-Jun-2021 16:38:41
 */

#ifndef NOTCH_H
#define NOTCH_H

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Numerator Length    : 3
 * Denominator Length  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */


#define NOTCH_NUMERATOR 3
#define NOTCH_DENOMINATOR 3

float NOTCH_NUM[3] = {
     0.9904984832,   -1.602660179,   0.9904984832
};


float NOTCH_DEN[3] = {
                0,   -1.602660179,   0.9809969068
};

#endif
